# Generated by Django 3.2.4 on 2021-11-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(help_text='autor of messages', max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(help_text='title of messages', max_length=100),
        ),
    ]
