# Generated by Django 3.2.4 on 2021-11-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20211110_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='numero_paginas',
            field=models.IntegerField(default=1, help_text='numero de paginas del texto', max_length=1000),
            preserve_default=False,
        ),
    ]
