# Generated by Django 3.2.4 on 2021-11-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_libro_numero_paginas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='numero_paginas',
            field=models.IntegerField(help_text='numero de paginas del texto'),
        ),
    ]
