# Generated by Django 3.2.4 on 2021-11-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_alter_libro_numero_paginas'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='anio_publicacion',
            field=models.DateField(help_text='anio de publicacion', null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(help_text='ISBN del libro', max_length=100, null=True),
        ),
    ]
