# Generated by Django 3.2.4 on 2021-11-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_auto_20211110_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='marca del vehiculo', max_length=100)),
                ('modelo', models.CharField(help_text='modelo del vehiculo', max_length=100)),
                ('cilindraje', models.FloatField(help_text='ingresa el cilindraje')),
            ],
        ),
    ]
