# Generated by Django 3.2.4 on 2021-11-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_autos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='autos',
            new_name='Auto',
        ),
    ]
