# Generated by Django 3.2.4 on 2021-11-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_rename_autos_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='marca de la computadora', max_length=100)),
                ('modelo', models.CharField(help_text='modelo del computador', max_length=100)),
                ('ram', models.CharField(help_text='capacidad de la memoria ram', max_length=10)),
                ('almacenamiento', models.CharField(help_text='almacenamiento', max_length=15)),
                ('procesador', models.CharField(help_text='procesador', max_length=100)),
                ('pantalla', models.CharField(help_text='dimension de la pantalla', max_length=100)),
            ],
        ),
    ]
