# Generated by Django 3.2.4 on 2021-11-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0008_computadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='color',
            field=models.CharField(help_text='color', max_length=100, null=True),
        ),
    ]
